import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from scipy.ndimage import gaussian_filter
import beam_trace as bt  # Assumes beam_trace.py is in the same directory

# ==========================================
# 1. PSF ANALYSIS & CORRECTION FUNCTIONS
# ==========================================

def apply_dm_correction(phase_map, actuators_per_dia):
    """
    Simulates DM correction by high-pass filtering spatial frequencies 
    below the DM Nyquist limit.
    """
    if actuators_per_dia == 0:
        return phase_map
    # Sigma represents the actuator pitch in pixels
    sigma = (phase_map.shape[0] / actuators_per_dia) * 0.5
    low_spatial_freqs = gaussian_filter(phase_map, sigma=sigma)
    return phase_map - low_spatial_freqs

def analyze_psf(psf, perfect_psf, angular_pixel_scale, ao_label="N/A"):
    """
    Calculates Strehl, Encircled Energy (50/80), and Ellipticity.
    """
    ny, nx = psf.shape
    yy, xx = np.indices((ny, nx))
    center = (ny // 2, nx // 2)
    r_pix = np.sqrt((xx - center[1])**2 + (yy - center[0])**2)

    # Strehl Ratio
    strehl = np.max(psf) / np.max(perfect_psf)

    # Encircled Energy
    r_flat = r_pix.flatten()
    psf_flat = psf.flatten()
    idx = np.argsort(r_flat)
    ee_curve = np.cumsum(psf_flat[idx]) / np.sum(psf_flat)
    r_sorted = r_flat[idx] * angular_pixel_scale
    
    ee50 = r_sorted[np.searchsorted(ee_curve, 0.50)]
    ee80 = r_sorted[np.searchsorted(ee_curve, 0.80)]

    # Ellipticity via Gaussian Fit from beam_trace
    x_ld = (xx - center[1]) * angular_pixel_scale
    y_ld = (yy - center[0]) * angular_pixel_scale
    fit = bt.fit_2d_gaussian(x_ld, y_ld, psf)
    metrics = bt.gaussian_fwhm_and_ellipticity(fit)

    return {
        "strehl": strehl,
        "ee50": ee50,
        "ee80": ee80,
        "ellipticity": metrics["ellipticity"],
        "fwhm_major": metrics["fwhm_major"],
        "ao_label": ao_label
    }

# ==========================================
# 2. SIMULATION SETUP
# ==========================================

# Path to FITS generated by mqtestbench_phasescreen_gen_v2.py
FITS_PATH = "phasescreens_median_dmScaled-1_radialScaled-0.fits"

try:
    with fits.open(FITS_PATH) as hdul:
        # Convert radians @ 500nm to OPD in meters
        maps = [ (hdul[lbl].data * 500e-9) / (2 * np.pi) for lbl in ['GL1', 'GL2', 'GL3', 'FA'] ]
        pixel_scale = hdul[1].header['PIXSCALE']
except FileNotFoundError:
    print(f"Error: {FITS_PATH} not found. Run the phase screen generator first.")
    exit()

# Physical Constants
WAVELENGTH = 589e-9  # Sodium LGS wavelength
D_BEAM = 0.013       # 13 mm test bench diameter
SOURCE_Z = -3.25     # Origin of converging beams
NPIX_PUPIL = 256
PAD_FACTOR = 4       # For PSF sampling
ANGULAR_SCALE = 1.0 / PAD_FACTOR  # in units of lambda/D

# Build Bench
bench = bt.OpticalBench3D()
z_pos = [-0.024, -0.048, -0.096, -2.50]
labels = ["GL1", "GL2", "GL3", "FA"]
v_wind = [0.7, 1.0, 1.4, 0.4] # Hz rotation

for m, z, lbl, v in zip(maps, z_pos, labels, v_wind):
    bench.add(bt.RotatingPhaseScreen3D(
        point=[0, 0, z], normal=[0, 0, 1], opd_map=m,
        map_extent_m=m.shape[0]*pixel_scale, angular_velocity=2*np.pi*v, label=lbl
    ))


# ==========================================
# 3. FIELD SWEEP & ANALYSIS
# ==========================================

# 1. Generate Perfect PSF (Diffraction Limited)
yy, xx = np.indices((NPIX_PUPIL, NPIX_PUPIL))
center = NPIX_PUPIL // 2
# Define the circular pupil mask (radius 64 pixels for a 256 grid)
pupil_mask = (np.sqrt((xx - center)**2 + (yy - center)**2) <= 64).astype(float)

perfect_sample = {
    "mask": pupil_mask.astype(bool),
    "amplitude": pupil_mask,          # Added this to fix the KeyError!
    "phase_map_rad": np.zeros((NPIX_PUPIL, NPIX_PUPIL)),
    "dx": D_BEAM / NPIX_PUPIL
}

# Now this call will have all the keys it needs
perfect_psf_pack = bt.psf_from_plane_sample(perfect_sample)
perfect_psf = perfect_psf_pack["psf"]

# 2. Radial Sweep
field_angles = np.linspace(0, 10, 6)  # arcmin
ao_modes = {"Uncorrected": 0, "TestBench_DM": 10, "Real_DM": 35}
all_results = {mode: [] for mode in ao_modes}

print(f"Starting field sweep across {len(field_angles)} points...")

for mode, acts in ao_modes.items():
    print( f"looking at mode:{mode}" )
    for theta in field_angles:
        # Trace off-axis beam
        beam = bt.make_converging_beam_from_field_angles(
            theta_x_rad=np.deg2rad(theta/60.0), theta_y_rad=0,
            source_plane_z=SOURCE_Z, pupil_point=np.array([0,0,0]),
            beam_diameter=D_BEAM, wavelength=WAVELENGTH,
            label=f"th_{theta}", nrings=3, nphi=12
        )
        
        # Sample Phase
        sample = bt.sample_beam_phase_amplitude_on_pupil_plane(
            beam, bench, np.array([0,0,0]), t=0.0, npix=NPIX_PUPIL
        )
        
        # Apply AO Correction & Analyze
        sample["phase_map_rad"] = apply_dm_correction(sample["phase_map_rad"], acts)
        psf_data = bt.psf_from_plane_sample(sample)
        
        stats = analyze_psf(psf_data["psf"], perfect_psf, ANGULAR_SCALE, ao_label=mode)
        all_results[mode].append(stats)

# ==========================================
# 4. PLOTTING RESULTS
# ==========================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for mode in ao_modes:
    strehls = [r["strehl"] for r in all_results[mode]]
    ee80s = [r["ee80"] for r in all_results[mode]]
    
    axes[0].plot(field_angles, strehls, 'o-', label=mode)
    axes[1].plot(field_angles, ee80s, 's--', label=mode)

axes[0].set_title("Strehl Ratio vs Field Angle")
axes[0].set_ylabel("Strehl")
axes[1].set_title("80% Encircled Energy Radius")
axes[1].set_ylabel("Radius [$\lambda/D$]")

for ax in axes:
    ax.set_xlabel("Field Angle [arcmin]")
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()


# import beam_trace as bt


# # read in phase screens fits files

# # build test bench instances using the phase screen maps read in
# #   -look at function build_main_example() <- build like this but not encapsulated in single function so we can clearly see development of components 
 

# # propogate 13mm beam pupil to pupil plane ( similar to build_main_example()) at different 
# #   radial coordinates along a single line from the center to outer perimeter


# # rotate phase screens and store pupil plane time series for each initial position instance 


# # consider no correction, correction with test bench DM (10 actuators per diameter) and correction with real DM (35 actuators diameter). Spatial filter (LPF) at DM nyquist 

# # create a generalised function that takes a pupil image, pads it and then focuses the beam to a PSF 
# #   first of all what physics do we need to account for in the simulation for the fact the beam is slightly off axis when originating off center from the FOV?
# # the goal is to generate the PSF and store/plot the statistics of the PSF across FOV in each case 
# #    - fit Gaussian
# #    - Strehl
# #    - FHWM
# #   - ellipticity 
# #    - encircled energy 




# extended goal : add radial ramp on phase screen and see how we can vary seeing!   
